require('everdro1d.core.modules.gui')
require('everdro1d.core.modules.native-cmp')
require('everdro1d.core.modules.netrw')
require('everdro1d.core.modules.rename-window')
require('everdro1d.core.modules.diagnostics')
