# ./.tmuxinator.yml

name: neovim-dotfiles
root: <%= ENV["PROJECTS"] %>/neovim-dotfiles/

on_project_start: ./setup-testing.sh
startup_window: editor
on_project_stop: rm -i ~/.config/nvim

windows:
  - editor: nvim .
  - term:
  - git-lg: lazygit
  - flake-term:
      root: <%= ENV["NIX_DOTFILES"] %>
